### ISSUE TITLE
Bug Report: Paladin/Warlock Mount not working

### ISSUE THREAD

**Issue by 5ut** [SanctuaryWoW/Bugtracker#12]
**Bug Description**
Paladin Summon Charger spell not working but buff is displayed, if I summon warhorse both buffs are showing, maybe because DM isn't out the charger cant be summoned ? 

![image](https://github.com/SanctuaryWoW/Bugtracker/assets/56796491/e8c0af0d-9ac5-4492-9380-4243cd7fc2f8)

**Expected Behavior**
If on proper patch, allow mount. If not on proper patch, do not cast spell or allow to learn.

Submitted by Bodo

**Comment by Sanctuary-wow** [comment]
This is working as intended. The mount spell will not be obtainable by any players before the appropriate patch. 
I double checked if it works on 1.12 vs 1.2 and working perfectly. As well, the quest chain does not spawn prior to the proper patch.
