### ISSUE TITLE
Bug Report: Combo Points drop while tabbing targets

### ISSUE THREAD

**Issue by 5ut** [SanctuaryWoW/Bugtracker#13]
**Bug Description**
Combo points dropping from rogue (and I assume druid as well) when tab switching targets. 

**Expected Behavior**
Affects Pve/Pvp because many of my macros will just suddenly drop combo points, resulting in a major dps loss. To my knowledge this is not blizzlike either, but its common on a lot of fresh vmangos servers for some reason.
Only drop points if they target to another NPC and attack them or cast another spell. 

Submitted by zulgen

**Comment by Sanctuary-wow** [comment]
https://wowpedia.fandom.com/wiki/Combo_point

"Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected."
https://wowwiki-archive.fandom.com/wiki/Patch_1.4.0

Then it doesn't change until TBC prepatch
"Combo points added to a target should not be reset until you add a combo point to a different target."
https://wowpedia.fandom.com/wiki/Patch_2.0.3
