### ISSUE TITLE
Bug Report: Instant logout & jump disconnect

### ISSUE THREAD

**Issue by 5ut** [SanctuaryWoW/Bugtracker#4]
**Bug Description**
Instant logout outside of rested areas, additionally if you logout while jumping sometimes it disconnects you from the server rather than prompting the error message "you can't logout now", however I cannot do this consistantly

**Expected Behavior**
Instant logout should only occur in rested areas.
Jumping while logging off shouldn't allow log off.

Submitted by Markiboi

**Comment by 5ut** [comment]
The instant logout is likely caused by GM being enabled. 
The jumping issue could be related.

**Comment by Sanctuary-wow** [comment]
Cannot recreate. Closing.
