### ISSUE TITLE
Bug Report: Milly's Harvest aggro

### ISSUE THREAD

**Issue by 5ut** [SanctuaryWoW/Bugtracker#6]
**Bug Description**
Milly's Harvest, looting the fruit buckets does not aggro the mobs nearby.

**Expected Behavior**
Each bucket should be guarded by one or two mobs, not sure which ones will be guarding which buckets

Submitted by Markiboi

**Comment by Sanctuary-wow** [comment]
Doesn't appear to be broken. Mobs here will aggro by proximity not by looting.
